export const places = [
  {
    id: 1,
    name: "Hogwarts",
    icon: "harry-potter.png",
    background: "hogwarts_sunny.png",
    routename: "Hogwarts",
  },
  {
    id: 2,
    name: "The Shire",
    icon: "ring.png",
    background: "hobbiton_sunny.png",
    routename: "Shire",
  },
  {
    id: 3,
    name: "King's Landing",
    icon: "throne.png",
    background: "kingslanding_sunny.png",
    routename: "Kingslanding",
  },
  {
    id: 4,
    name: "Wakanda",
    icon: "superhero.png",
    background: "wakanda_sunny.png",
    routename: "Wakanda",
  },
  {
    id: 5,
    name: "Gotham City",
    icon: "batman-logo.png",
    background: "gotham_sunny.png",
    routename: "Gotham",
  },
  {
    id: 6,
    name: "Asgard",
    icon: "thor-hammer.png",
    background: "AsgardDarkWorld.webp",
    routename: "Asgard",
  },
  {
    id: 7,
    name: "Tatooine",
    icon: "light-saber.png",
    background: "tatooine_sunny.png",
    routename: "Tatooine",
  },
  {
    id: 8,
    name: "Arendelle",
    icon: "snowflake.png",
    background: "arendelle_sunny.png",
    routename: "Arendelle",
  },
  {
    id: 9,
    name: "Pandora",
    icon: "avatar.png",
    background: "pandora_sunny.jpeg",
    routename: "Pandora",
  },
];
